kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.089387613506034497
    roll: -0
    pitch: 0
    yaw: -2.9327387405498691e-05
  upper_arm:
    x: 0.00028532695393488993
    y: 0
    z: 0
    roll: 1.5706343433591938
    pitch: 0
    yaw: -2.6212740733999592e-05
  forearm:
    x: -0.425419045445463
    y: 0
    z: 0
    roll: 0.00035426155328976164
    pitch: 0.00080681172625173545
    yaw: -3.9748018592992895e-05
  wrist_1:
    x: -0.39252732921025874
    y: -0.00085184617587656089
    z: 0.11074575923260002
    roll: 0.0076917561667593747
    pitch: 0.0007361898417088433
    yaw: 4.8820671471793427e-05
  wrist_2:
    x: -3.8237518684338207e-06
    y: -0.094949021583690618
    z: 8.1999851159141228e-05
    roll: 1.5699327072503746
    pitch: 0
    yaw: 7.637985297725426e-06
  wrist_3:
    x: 6.6575792414914778e-05
    y: 0.082610044167395341
    z: -3.4232438398284863e-06
    roll: 1.5707548882038345
    pitch: 3.1415926535897931
    yaw: 3.1415532295209649
  hash: calib_3221091877572755834